<a href="https://colab.research.google.com/github/robitussin/CCADMACL_EXERCISES/blob/main/Exercise7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise 7

In [25]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from mlxtend.frequent_patterns import apriori, association_rules
from mlxtend.frequent_patterns import fpgrowth

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [26]:
#reading data
url = "https://github.com/robitussin/CCADMACL_EXERCISES/blob/ff41fec98bd270f4bbeedb9b8849ae21fdeadfee/Groceries_dataset.csv?raw=true"
dataset = pd.read_csv(url)

dataset.head()

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

   Member_number        Date   itemDescription
0           1808  21-07-2015    tropical fruit
1           2552  05-01-2015        whole milk
2           2300  19-09-2015         pip fruit
3           1187  12-12-2015  other vegetables
4           3037  01-02-2015        whole milk

In [27]:
client_basket = dataset.groupby(['Member_number', 'Date'])['itemDescription'].apply(lambda x: ', '.join(x))
client_basket

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

Member_number  Date
1000           15-03-2015     sausage, whole milk, semi-finished bread, yogurt
               24-06-2014                      whole milk, pastry, salty snack
               24-07-2015                         canned beer, misc. beverages
               25-11-2015                            sausage, hygiene articles
               27-05-2015                             soda, pickled vegetables
                                                   ...
4999           24-01-2015    tropical fruit, berries, other vegetables, yog...
               26-12-2015                                 bottled water, herbs
5000           09-03-2014                        fruit/vegetable juice, onions
               10-02-2015           soda, root vegetables, semi-finished bread
               16-11-2014                       bottled beer, other vegetables
Name: itemDescription, Length: 14963, dtype: object

### 1. Apply one-hot encoding

In [28]:
## put your answer here

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

2. Use the Apriori Algorithm to find the most frequent sets

In [29]:
## put your answer here

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

3. Display the association rules using the lift metric

In [30]:
## put your answer here

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)